import tkinter as tk
import tkinter.ttk as ttk
a= "PATH//GOES//HERE"
root =tk.Tk()
mainframe= ttk.Frame(padding=10)
excelframemain = ttk.Frame(master=mainframe)
excelframelabel= ttk.Frame(master=excelframemain)
excelframebutton = ttk.Frame(master=excelframemain)
excellabel = ttk.Label(master =excelframelabel, text="Excel sheet file location",width=25,padding=5)
excellabel.pack()
excelpath = ttk.Label(master =excelframelabel, text=a,width=25,)
excelpath.pack()
excelframelabel.pack(side=tk.LEFT)
excelbutton = ttk.Button( master =excelframebutton, text="select file",width=15)
excelbutton.pack()
excelframebutton.pack(side=tk.RIGHT)
excelframemain.pack(fill=tk.BOTH)

gdbframemain = ttk.Frame(master=mainframe)
gdbframelabel= ttk.Frame(master=gdbframemain)
gdbframebutton = ttk.Frame(master=gdbframemain)
gdblabel = ttk.Label(master =gdbframelabel, text="gdb sheet file location",width=25,padding=5)
gdblabel.pack()
gdbpath = ttk.Label(master =gdbframelabel, text=a,width=25)
gdbpath.pack()
gdbframelabel.pack(side=tk.LEFT)
gdbbutton = ttk.Button( master =gdbframebutton, text="select file",width=15)
gdbbutton.pack()
gdbframebutton.pack(side=tk.RIGHT)
gdbframemain.pack(fill=tk.BOTH)

outputframemain = ttk.Frame(master=mainframe)
outputframelabel= ttk.Frame(master=outputframemain)
outputframebutton = ttk.Frame(master=outputframemain)
outputlabel = ttk.Label(master =outputframelabel, text="output sheet folder location",width=25,padding=5)
outputlabel.pack()
outputpath = ttk.Label(master =outputframelabel, text=a,width=25)
outputpath.pack()
outputframelabel.pack(side=tk.LEFT)
outputbutton = ttk.Button( master =outputframebutton, text="select folder",width=15)
outputbutton.pack()
outputframebutton.pack(side=tk.RIGHT)
outputframemain.pack(fill=tk.BOTH)

logframemain = ttk.Frame(master=mainframe)
logframelabel= ttk.Frame(master=logframemain)
logframebutton = ttk.Frame(master=logframemain)
loglabel = ttk.Label(master =logframelabel, text="log folder location",width=25,padding=5)
loglabel.pack()
logpath = ttk.Label(master =logframelabel, text=a,width=25)
logpath.pack()
logframelabel.pack(side=tk.LEFT)
logbutton = ttk.Button( master =logframebutton, text="select folder",width=15)
logbutton.pack()
logframebutton.pack(side=tk.RIGHT)
logframemain.pack(fill=tk.BOTH)

run = ttk.Button(text="run",master=mainframe)
run.pack(fill= tk.BOTH)
mainframe.pack(fill=tk.BOTH)
root.mainloop()